name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Set the image tag as an environment variable
    - name: Set image tag
      id: image_tag
      run: echo "tag=$(date +%s)" >> $GITHUB_ENV

    # Build the Docker image with the defined tag
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/dockdv/webdav/webdav:${{ env.tag }}

    # Push the Docker image to the registry
    - name: Push Docker image to registry
      run: docker push ghcr.io/dockdv/webdav/webdav:${{ env.tag }}
      if: github.event_name == 'push'
